Add option to draw easymotion on top
asvetliakov/vscode-neovim pull request #280
Opened 2020-06-07 05:05 UTC by jhgarner

The original easymotion extension drew text directly on top of the
target characters. The fork drew text behind the target characters.
This commit adds an option to pick whichever you want.
Even if you pick on top of the target, you won't end up with broken
linting.

closes #276

2020-06-08 03:44 UTC, jhgarner commented
I think there are some inconsistencies with motions at the ends of lines. I'll try to fix those and give a comment when that's done.

2020-06-11 04:04 UTC, jhgarner commented
I think this is finally working with almost perfect accuracy. The code is a bit more complicated, but it makes using the plugin significantly nicer. If I don't catch any problems in the next few days, I'll remove the WIP tag.

2020-06-11 06:39 UTC, theol0403 commented
It seems to work great. One thing I noticed is that the text overlay is *slightly* too far to the left. 

![image](https://user-images.githubusercontent.com/16546293/84353203-8e95eb80-ab73-11ea-984c-de3564108578.png)
![image](https://user-images.githubusercontent.com/16546293/84353101-5d1d2000-ab73-11ea-815d-fb51a987ae6f.png)

This causes the shadow of the gutter to occasionally overlap the text:
![image](https://user-images.githubusercontent.com/16546293/84353139-732ae080-ab73-11ea-8e81-8c73912b4a13.png)

2020-06-13 03:37 UTC, jhgarner commented
I wonder if that has to do with the magic number of 8 that's used for the margin and width. Maybe there's some way to dynamically pick the right thing? I'll look into that.

2020-06-18 03:13 UTC, jhgarner commented
@theol0403 I've switched the units from px to ch. I didn't see the problem on my machine so let me know if that fixed it for you.

2020-06-18 03:34 UTC, theol0403 commented
Yep, that fixed it. It now works beautifully on my machine :+1:

2020-06-20 06:13 UTC, jhgarner commented
I've removed the WIP from the title. It seems to work pretty well.

2020-08-05 13:21 UTC, Shatur95 commented
The feature I missing. Offsetting lines makes easymotion very awkward to use. But I see that @asvetliakov is busy now. Maybe it would be better to let some right to the contributors, such as @jhgarner?

2020-08-23 21:03 UTC, asvetliakov commented
Will look/review the PR within next week

2020-09-05 20:08 UTC, Shatur95 commented
@jhgarner, could you resolve merge conflicts?

2020-09-05 20:30 UTC, asvetliakov requested changes

2020-09-05 20:30 UTC, asvetliakov commented on package.json
> +				"vscode-neovim.easymotionOnTop": {
let's rename to `textDecorationsAtTop`

2020-09-05 20:30 UTC, asvetliakov commented on package.json
> +		"vsce": "^1.79.3",
not needed here

2020-09-05 20:30 UTC, asvetliakov commented on src/controller.ts
>          }
This should be in `highlight_manager.ts`

2020-09-05 20:30 UTC, asvetliakov commented on src/controller.ts
> +                    if (Utils.getEasymotionOnTop()) {
Pass an option to HL manager constructor. Getting workspace configuration every time is costly

2020-09-05 20:30 UTC, asvetliakov commented on src/controller.ts
> +                        const col = Utils.convertByteNumToCharNumOnTop(line, colNum);
No need for another function - `convertByteNumToCharNum()` is used now only for decorations. Also check how does it work with tabs

2020-09-05 20:30 UTC, asvetliakov commented on src/controller.ts
> +                        // 8 seems to be a magic number. It works for me, but I'm not sure why...
Not sure i understand this comment

2020-09-05 20:30 UTC, asvetliakov commented on src/controller.ts
> +                                        margin: `0 0 0 -${Math.min(
What will happen if we won't use a negative right margin? Mind a share a screenshot?

2020-09-05 20:30 UTC, asvetliakov commented on src/utils.ts
> +            return currCharNum + (col - totalBytes);
Why this is needed? Anyway, better to modify the existing function rather than creating a copy with slighly changed behavior

2020-09-05 20:35 UTC, Shatur95 commented
Maybe it would be easier to just open new PR since master have a lot of changes?

2020-09-05 20:40 UTC, asvetliakov commented
>Maybe it would be easier to just open new PR since master have a lot of changes?

Agree

2020-09-07 03:15 UTC, jhgarner commented
Thanks for the review. I'll close this issue, refactor it for the new master, and fix the comments you brought up.

2020-09-07 03:15 UTC, closed without merging

2020-09-08 21:09 UTC, jrolfs commented
↓ Can't wait to get rid of this! ↓
<img width="1532" alt="vscode-neovim--absolute-text-decorations" src="https://user-images.githubusercontent.com/288160/92527962-c517ec80-f1dc-11ea-88eb-e8094a73187d.png">


If anyone's looking for a workaround in the meantime though...

```json
  "customizeUI.stylesheet": {
    ".monaco-editor span[class*=' ced-1-TextEditorDecorationType']:not([class*=' ced-1-TextEditorDecorationType1'])::before": "position: absolute;"
  }
```