fix: cursor is left behind
asvetliakov/vscode-neovim pull request #305
Opened 2020-07-31 08:49 UTC by kuator

https://stackoverflow.com/questions/49997089/vscode-how-to-set-that-when-i-press-ctrl-up-or-down-arrow-the-cursor-move-wi
Vs Code, by default, doesn't update cursor position after scrolling, which is not the case in vim. This pr makes experience more similar to scrolling in vim.

2020-09-05 14:22 UTC, asvetliakov commented
probably need a setting here

2020-09-06 08:00 UTC, kuator commented
Kind of like this?

2020-09-06 13:20 UTC, asvetliakov requested changes

2020-09-06 13:20 UTC, asvetliakov commented on src/commands_controller.ts
> +        const settings = vscode.workspace.getConfiguration(EXT_NAME);
Pass the option as constructor param from the main_controller, don't query it every time for perf reasons

2020-09-07 08:46 UTC, kuator commented
Is it better?

2020-09-07 15:20 UTC, asvetliakov requested changes
Almost 😄

2020-09-07 15:20 UTC, asvetliakov commented on src/main_controller.ts
> +        await this.client.uiAttach(this.NEOVIM_WIN_WIDTH, this.NEOVIM_WIN_HEIGHT, {
Broken merge ? remove

2020-09-07 15:39 UTC, asvetliakov approved these changes

2020-09-08 00:13 UTC, asvetliakov commented
Fixes #236

2020-09-08 01:19 UTC, asvetliakov commented
Thank you for your PR!

2020-09-08 01:19 UTC, merged

2021-01-12 13:42 UTC, d4h0 commented
@kuator: Thanks a million! This problem was one of the main reason why I stopped using this extension in the past.

@asvetliakov: Is there a reason why this can not be activated by default?

And a million thanks to you as well for creating the extension – without the now fixed cursor problem, it's fantastic!

2021-01-13 06:58 UTC, kuator commented
> @kuator: Thanks a million! This problem was one of the main reason why I stopped using this extension in the past.
> 
> @asvetliakov: Is there a reason why this can not be activated by default?
> 
> And a million thanks to you as well for creating the extension – without the now fixed cursor problem, it's fantastic!

😢thanks